#!/usr/bin/env php
<?php
/**
 * Unity Runner
 *
 * (c) Tom Morton
 *
 */

require 'vendor/autoload.php';


use Unity\Event;
use Unity\Config;
use Unity\Config\ConsoleConfig;
use Unity\Config\UserConfig;
use Unity\CommandRunner;
use Unity\Command\TestsCommand;
use Unity\Command\RunCommand;
use Unity\Command\ConfigCommand;

// Error handling
$runner = new \League\BooBoo\Runner();
$runner->pushFormatter(new \League\BooBoo\Formatter\CommandLineFormatter);
$runner->register();

// Using League's CLImate for Output
$climate = new \League\CLImate\CLImate;

// Load the Composer file for Unity
$unityComposer = \Unity\Unity::getComposerFile();

// Instantiate Unity
$unity = new \Unity\Unity(__DIR__, $unityComposer->version);

// Configuration
Config::register($unity);
$unity->get('config')->attach(new ConsoleConfig($unity->config),10);
$unity->config->attach(new UserConfig($unity->config));

// Register the Event Class
Event::register($unity);

// Register the Command Class
CommandRunner::registerService($unity);

// Console Commands
TestsCommand::register($unity);
RunCommand::register($unity);
ConfigCommand::register($unity);

$unity->get('command')->run();
